// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwrzSSX3hRPLBGgI17ubkuL8jzp1x3c2g',
    appId: '1:305850456819:web:e409d037d2148c04f53586',
    messagingSenderId: '305850456819',
    projectId: 'cable-admin-lite',
    authDomain: 'cable-admin-lite.firebaseapp.com',
    storageBucket: 'cable-admin-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6uN8U-NBc5aUbcjgiGMV7X10ViYAqZo0',
    appId: '1:305850456819:android:837d0e659bff1e2df53586',
    messagingSenderId: '305850456819',
    projectId: 'cable-admin-lite',
    storageBucket: 'cable-admin-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjeXQzA2j2Vi7iZ1PaXcSYjZcYu5m8sE',
    appId: '1:305850456819:ios:6ebd4cdc1998961ff53586',
    messagingSenderId: '305850456819',
    projectId: 'cable-admin-lite',
    storageBucket: 'cable-admin-lite.firebasestorage.app',
    iosBundleId: 'com.example.cableOperatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjeXQzA2j2Vi7iZ1PaXcSYjZcYu5m8sE',
    appId: '1:305850456819:ios:6ebd4cdc1998961ff53586',
    messagingSenderId: '305850456819',
    projectId: 'cable-admin-lite',
    storageBucket: 'cable-admin-lite.firebasestorage.app',
    iosBundleId: 'com.example.cableOperatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwrzSSX3hRPLBGgI17ubkuL8jzp1x3c2g',
    appId: '1:305850456819:web:6b4b438b9e1f34cff53586',
    messagingSenderId: '305850456819',
    projectId: 'cable-admin-lite',
    authDomain: 'cable-admin-lite.firebaseapp.com',
    storageBucket: 'cable-admin-lite.firebasestorage.app',
  );
}
